# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import viagem_pb2 as viagem__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in viagem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgenciaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pacote_viagem = channel.unary_stream(
                '/Viagem.Agencia/pacote_viagem',
                request_serializer=viagem__pb2.PacotePedido.SerializeToString,
                response_deserializer=viagem__pb2.PacoteResposta.FromString,
                _registered_method=True)


class AgenciaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def pacote_viagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgenciaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'pacote_viagem': grpc.unary_stream_rpc_method_handler(
                    servicer.pacote_viagem,
                    request_deserializer=viagem__pb2.PacotePedido.FromString,
                    response_serializer=viagem__pb2.PacoteResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Viagem.Agencia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Viagem.Agencia', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Agencia(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def pacote_viagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Viagem.Agencia/pacote_viagem',
            viagem__pb2.PacotePedido.SerializeToString,
            viagem__pb2.PacoteResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CompanhiaAereaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reserva_passagem = channel.unary_unary(
                '/Viagem.CompanhiaAerea/reserva_passagem',
                request_serializer=viagem__pb2.PassagemPedido.SerializeToString,
                response_deserializer=viagem__pb2.PassagemResposta.FromString,
                _registered_method=True)
        self.rollback_reserva = channel.unary_unary(
                '/Viagem.CompanhiaAerea/rollback_reserva',
                request_serializer=viagem__pb2.RollbackPassagemPedido.SerializeToString,
                response_deserializer=viagem__pb2.RollbackPassagemResposta.FromString,
                _registered_method=True)


class CompanhiaAereaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reserva_passagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rollback_reserva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompanhiaAereaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reserva_passagem': grpc.unary_unary_rpc_method_handler(
                    servicer.reserva_passagem,
                    request_deserializer=viagem__pb2.PassagemPedido.FromString,
                    response_serializer=viagem__pb2.PassagemResposta.SerializeToString,
            ),
            'rollback_reserva': grpc.unary_unary_rpc_method_handler(
                    servicer.rollback_reserva,
                    request_deserializer=viagem__pb2.RollbackPassagemPedido.FromString,
                    response_serializer=viagem__pb2.RollbackPassagemResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Viagem.CompanhiaAerea', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Viagem.CompanhiaAerea', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompanhiaAerea(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reserva_passagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Viagem.CompanhiaAerea/reserva_passagem',
            viagem__pb2.PassagemPedido.SerializeToString,
            viagem__pb2.PassagemResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rollback_reserva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Viagem.CompanhiaAerea/rollback_reserva',
            viagem__pb2.RollbackPassagemPedido.SerializeToString,
            viagem__pb2.RollbackPassagemResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HotelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reserva_hotel = channel.unary_unary(
                '/Viagem.Hotel/reserva_hotel',
                request_serializer=viagem__pb2.HotelPedido.SerializeToString,
                response_deserializer=viagem__pb2.HotelResposta.FromString,
                _registered_method=True)
        self.rollback_hotel = channel.unary_unary(
                '/Viagem.Hotel/rollback_hotel',
                request_serializer=viagem__pb2.RollbackHotelPedido.SerializeToString,
                response_deserializer=viagem__pb2.RollbackHotelResposta.FromString,
                _registered_method=True)


class HotelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reserva_hotel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rollback_hotel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reserva_hotel': grpc.unary_unary_rpc_method_handler(
                    servicer.reserva_hotel,
                    request_deserializer=viagem__pb2.HotelPedido.FromString,
                    response_serializer=viagem__pb2.HotelResposta.SerializeToString,
            ),
            'rollback_hotel': grpc.unary_unary_rpc_method_handler(
                    servicer.rollback_hotel,
                    request_deserializer=viagem__pb2.RollbackHotelPedido.FromString,
                    response_serializer=viagem__pb2.RollbackHotelResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Viagem.Hotel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Viagem.Hotel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Hotel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reserva_hotel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Viagem.Hotel/reserva_hotel',
            viagem__pb2.HotelPedido.SerializeToString,
            viagem__pb2.HotelResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rollback_hotel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Viagem.Hotel/rollback_hotel',
            viagem__pb2.RollbackHotelPedido.SerializeToString,
            viagem__pb2.RollbackHotelResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CarroStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reserva_carro = channel.unary_unary(
                '/Viagem.Carro/reserva_carro',
                request_serializer=viagem__pb2.CarroPedido.SerializeToString,
                response_deserializer=viagem__pb2.CarroResposta.FromString,
                _registered_method=True)
        self.rollback_carro = channel.unary_unary(
                '/Viagem.Carro/rollback_carro',
                request_serializer=viagem__pb2.RollbackCarroPedido.SerializeToString,
                response_deserializer=viagem__pb2.RollbackCarroResposta.FromString,
                _registered_method=True)


class CarroServicer(object):
    """Missing associated documentation comment in .proto file."""

    def reserva_carro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rollback_carro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarroServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reserva_carro': grpc.unary_unary_rpc_method_handler(
                    servicer.reserva_carro,
                    request_deserializer=viagem__pb2.CarroPedido.FromString,
                    response_serializer=viagem__pb2.CarroResposta.SerializeToString,
            ),
            'rollback_carro': grpc.unary_unary_rpc_method_handler(
                    servicer.rollback_carro,
                    request_deserializer=viagem__pb2.RollbackCarroPedido.FromString,
                    response_serializer=viagem__pb2.RollbackCarroResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Viagem.Carro', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Viagem.Carro', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Carro(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def reserva_carro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Viagem.Carro/reserva_carro',
            viagem__pb2.CarroPedido.SerializeToString,
            viagem__pb2.CarroResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rollback_carro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Viagem.Carro/rollback_carro',
            viagem__pb2.RollbackCarroPedido.SerializeToString,
            viagem__pb2.RollbackCarroResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
